name: Script CI

on: [push]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-20.04, macos-11.0]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo make install-deps
    - name: make check
      run: make check
